services:
- type: web
  name: Flox
  runtime: docker
  repo: https://github.com/kenx54/Flox
  plan: free
  envVars:
  - key: TMDB_KEY
    sync: false
  - key: PORT
    sync: false
  - key: TRANSPORT_ROUTES
    sync: false
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
